# Generated by Django 6.1 on 2026-09-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('iso_2', models.CharField(max_length=2)),
                ('iso_3', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pseudonimo', models.CharField(max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_defuncion', models.DateField(null=True)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.pais')),
            ],
        ),
    ]
