# Generated by Django 6.1 on 2026-09-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0002_pais_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Código', models.CharField(max_length=5)),
                ('Comuna', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='fecha_defuncion',
            new_name='Fecha Defunción',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='fecha_nacimiento',
            new_name='Fecha Nacimiento',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='pseudonimo',
            new_name='Pseudónimo',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='Categoría',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='Descripción',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='iso_2',
            new_name='ISO 2',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='iso_3',
            new_name='ISO 3',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='nacionalidad',
            new_name='Nacionalidad',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='nombre',
            new_name='País',
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.ForeignKey(db_column='nacionalidad', on_delete=django.db.models.deletion.CASCADE, to='biblio_app.pais'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calle', models.CharField(max_length=100)),
                ('Número', models.CharField(max_length=10, null=True)),
                ('Departamento/Oficina', models.CharField(max_length=10, null=True)),
                ('comuna', models.ForeignKey(db_column='comuna', on_delete=django.db.models.deletion.CASCADE, to='biblio_app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('web', models.URLField(max_length=254, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.direccion')),
            ],
        ),
    ]
