# Generated by Django 6.1 on 2026-09-30 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0003_comuna_rename_fecha_defuncion_autor_fecha_defunción_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_edicion', models.DateField(verbose_name='Fecha Edición')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Data específica de una publicación realizada por una editorial.',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('web', models.URLField(null=True, verbose_name='WWW')),
                ('correo', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Datos de empresas encargadas de publicaciones.',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Data de estado físico de ejemplares en la biblioteca.',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=30, verbose_name='Género Literario')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Géneros literarios asociados a subgéneros.',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=30, verbose_name='Idioma')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Data de idiomas para asociar a publicaciones.',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=50, verbose_name='Código Barras')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.estado')),
            ],
            options={
                'db_table_comment': 'Copias de un libro disponibles para préstamos en biblioteca.',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('paginas', models.IntegerField(verbose_name='Cantidad Páginas')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Data específica de libros publicados pertenecientes a la bilbioteca.',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Préstamo')),
                ('fecha_devolucion', models.DateTimeField(verbose_name='Fecha Devolución')),
                ('fecha_retorno', models.DateTimeField(null=True, verbose_name='Fecha Retorno')),
            ],
            options={
                'db_table_comment': 'Registro de préstamo de libros en la biblioteca.',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Provincias de Chile, data de SUBDERE. Pertenece a una región específica.',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('region', models.CharField(max_length=30, verbose_name='Región')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Regiones de Chile, data de SUBDERE.',
            },
        ),
        migrations.CreateModel(
            name='SubGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenero', models.CharField(max_length=30, verbose_name='Sub-Género Literario')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.genero')),
            ],
            options={
                'db_table_comment': 'Subgéneros literarios asociados a publicaciones/libros.',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Código')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Data de ubicación física de ejemplares en la biblioteca.',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('correo', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('contrasenia', models.CharField(max_length=128, null=True)),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Registro de usuarios de biblioteca.',
            },
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AlterModelTableComment(
            name='autor',
            table_comment='Datos de autores asociados a publicaciones/libros.',
        ),
        migrations.AlterModelTableComment(
            name='biblioteca',
            table_comment='Datos de biblioteca.',
        ),
        migrations.AlterModelTableComment(
            name='comuna',
            table_comment='Comunas de Chile, data de SUBDERE. Pertenece a una provincia específica.',
        ),
        migrations.AlterModelTableComment(
            name='direccion',
            table_comment='Provincias de Chile, data de SUBDERE. Pertenece a una región específica.',
        ),
        migrations.AlterModelTableComment(
            name='pais',
            table_comment='Información de paises del mundo, para asociar a autores y lectores.',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='Fecha Defunción',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='Fecha Nacimiento',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='Pseudónimo',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='Comuna',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='Código',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Calle',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Departamento/Oficina',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Número',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='ISO 2',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='ISO 3',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='Nacionalidad',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='País',
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='autor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_defuncion',
            field=models.DateField(null=True, verbose_name='Fecha Defunción'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AddField(
            model_name='autor',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(max_length=50, null=True, verbose_name='Pseudónimo'),
        ),
        migrations.AddField(
            model_name='autor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='codigo',
            field=models.CharField(default='00000', max_length=5, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comuna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comuna',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(max_length=10, null=True, verbose_name='Dpto/Oficina'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='pais',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='pais',
            name='iso_2',
            field=models.CharField(default='', max_length=2, verbose_name='ISO 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='iso_3',
            field=models.CharField(default='', max_length=3, verbose_name='ISO 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio_app.pais'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio_app.direccion'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='web',
            field=models.URLField(null=True, verbose_name='WWW'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.comuna'),
        ),
        migrations.AddField(
            model_name='editorial',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio_app.direccion'),
        ),
        migrations.AddField(
            model_name='edicion',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.editorial'),
        ),
        migrations.AddField(
            model_name='edicion',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.idioma'),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.biblioteca'),
        ),
        migrations.AddField(
            model_name='libro',
            name='edicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.edicion'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.libro'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.inventario'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='biblio_app.provincia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.region'),
        ),
        migrations.AddField(
            model_name='libro',
            name='subgenero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.subgenero'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.ubicacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.biblioteca'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio_app.direccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio_app.pais'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.usuario'),
        ),
        migrations.AddField(
            model_name='autor',
            name='nombre',
            field=models.CharField(default='Autor', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comuna',
            name='comuna',
            field=models.CharField(default='', max_length=60, verbose_name='Comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='pais',
            name='nacionalidad',
            field=models.CharField(default='', max_length=30, verbose_name='Nacionalidad'),
            preserve_default=False,
        ),
    ]
