# Generated by Django 6.1 on 2026-10-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0004_edicion_editorial_estado_genero_idioma_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
    ]
