# Generated by Django 6.1 on 2026-10-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0005_remove_comuna_created_at_remove_comuna_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='estado',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='genero',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='pais',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='region',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='subgenero',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name=1),
        ),
    ]
