# Generated by Django 6.1 on 2026-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0006_alter_autor_habilitado_alter_biblioteca_habilitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=40, verbose_name='Región'),
        ),
    ]
